function init(self)
	msg.post(".", "acquire_input_focus");
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	local p = vmath.vector3(action.x, action.y + 50, 0)
	local pieNode = gui.get_node("pie");
	gui.set_position(pieNode, p)
	if (gui.pick_node(gui.get_node("box"), p.x, p.y)) then
		gui.set_color(pieNode, vmath.vector3(0.5, 1, 1));
	else
		gui.set_color(pieNode, vmath.vector3(1, 1, 1));
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
